-- MySQL Script generated by MySQL Workbench
-- Thu Jun  5 10:38:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestor_os
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestor_os
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestor_os` DEFAULT CHARACTER SET utf8 ;
USE `gestor_os` ;

-- -----------------------------------------------------
-- Table `gestor_os`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestor_os`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `data_entrada` DATE NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_os`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestor_os`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `ano` INT NOT NULL,
  `data_entrada` DATE NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `situacao` VARCHAR(250) NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idproduto`),
  INDEX `fk_produto_cliente_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_produto_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `gestor_os`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_os`.`ordem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestor_os`.`ordem` (
  `idordem` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(19,4) NOT NULL,
  `data_entrega` DATE NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(250) NOT NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`idordem`),
  INDEX `fk_ordem_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_ordem_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `gestor_os`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
